In [2]:
import torch
x=torch.empty(5,3)
print(x)


tensor([[9.8830e+17, 3.5301e-12, 1.7743e+28],
        [6.8239e+16, 2.7685e+20, 1.8807e+31],
        [6.9983e+28, 3.0303e+24, 1.0305e+21],
        [7.1833e+22, 1.2102e+25, 1.2415e+28],
        [1.0804e+27, 4.5452e+30, 1.8910e+23]])


Part1:basic autograd (1)

In [3]:
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms

x=torch.tensor(4.,requires_grad=True)
w=torch.tensor(5.,requires_grad=True)
b=torch.tensor(6.,requires_grad=True)

y=x*w+b

y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

tensor(5.)
tensor(4.)
tensor(1.)


In [6]:
x=torch.randn(10,3)
y=torch.randn(10,2)


linear=nn.Linear(3,2)
print('w:',linear.weight)
print('b:',linear.bias)

criterion=nn.MSELoss()
optimizer=torch.optim.SGD(linear.parameters(),lr=0.01)

pred=linear(x)

loss=criterion(pred,y)
print('loss:',loss.item())

loss.backward()

print('dL/dw:',linear.weight.grad)
print('dL/db:',linear.bias.grad)

optimizer.step()

pred=linear(x)
loss=criterion(pred,y)
print('loss after one step optimization:',loss.item())

w: Parameter containing:
tensor([[-0.1795,  0.5468,  0.3508],
        [-0.0516, -0.0451,  0.5574]], requires_grad=True)
b: Parameter containing:
tensor([-0.0710,  0.5512], requires_grad=True)
loss: 1.8724663257598877
dL/dw: tensor([[-0.2744,  0.5080,  0.4745],
        [ 0.0007,  0.3392,  0.6306]])
dL/db: tensor([0.4986, 0.9170])
loss after one step optimization: 1.851020097732544


In [3]:
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [4]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
#grad在反向传播过程中是累加的,因此一般在反向传播之前需要把梯度清零

#1.没有清零
out2=x.sum()     
out2.backward()
print(x.grad)

#2.清零
out3=x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
