In [2]:
import torch
x=torch.tensor([5.5,3])
x=x.new_ones(5,3,dtype=torch.float64)
print(x)

x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0285, -0.6687, -1.7815],
        [ 0.7368,  0.4818,  1.4209],
        [-0.6471, -1.5157,  1.8429],
        [-0.1791,  1.4666, -0.9544],
        [-0.8886,  0.3517,  0.6063]])


In [4]:
#切片操作
y=x[0,:]
y+=1
print(y)
print(x[0,:])

tensor([0.3504, 2.5184, 3.3610])
tensor([0.3504, 2.5184, 3.3610])


In [5]:
#变形
y=x.view(15)
z=x.view(-1,5)
print(x.size())
print(y.size())
print(z.size())

torch.Size([5, 3])
torch.Size([15])
torch.Size([3, 5])


In [6]:
x+=1
print(x)
print(y)
#x变化 y也发生变化

tensor([[ 1.3504,  3.5184,  4.3610],
        [ 1.5188, -0.3170,  1.3121],
        [ 1.1224, -2.1150, -0.7608],
        [ 0.8740, -0.0525,  0.2478],
        [ 0.6540, -0.1729,  0.2842]])
tensor([ 1.3504,  3.5184,  4.3610,  1.5188, -0.3170,  1.3121,  1.1224, -2.1150,
        -0.7608,  0.8740, -0.0525,  0.2478,  0.6540, -0.1729,  0.2842])


In [7]:
#解决x变化 y变化的问题

x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[ 0.3504,  2.5184,  3.3610],
        [ 0.5188, -1.3170,  0.3121],
        [ 0.1224, -3.1150, -1.7608],
        [-0.1260, -1.0525, -0.7522],
        [-0.3460, -1.1729, -0.7158]])
tensor([ 1.3504,  3.5184,  4.3610,  1.5188, -0.3170,  1.3121,  1.1224, -2.1150,
        -0.7608,  0.8740, -0.0525,  0.2478,  0.6540, -0.1729,  0.2842])


In [8]:
#将标量Tensor变为一个Python Number
x=torch.randn(1)
print(x)
print(x.item())

tensor([1.4938])
1.4938164949417114


In [10]:
#矩阵的迹

x=torch.arange(1.,10.).view(3,3)
print(x)
y=torch.trace(x)
print(y.item())


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
15.0


In [12]:
#指定对角元素

x=torch.randn(3)
print('x:',x)
y=torch.diag(x)
print('y:',y)
z=torch.diag(x,1)  #指定偏移量
print('z:',z)

x: tensor([ 0.6651, -0.4681, -0.7364])
y: tensor([[ 0.6651,  0.0000,  0.0000],
        [ 0.0000, -0.4681,  0.0000],
        [ 0.0000,  0.0000, -0.7364]])
z: tensor([[ 0.0000,  0.6651,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.4681,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.7364],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])


In [13]:
#取得对角元素

x=torch.randn(3,3)
print('x:',x)
y=torch.diag(x,0)
print('y:',y)
z=torch.diag(x,1)   #1 默认向右上角偏移
print('z:',z)

x: tensor([[ 0.4556, -0.3504,  1.1313],
        [ 1.4284, -0.6833,  1.5558],
        [ 0.6125,  0.2744, -0.2523]])
y: tensor([ 0.4556, -0.6833, -0.2523])
z: tensor([-0.3504,  1.5558])


In [15]:
#取得矩阵的上三角/下三角矩阵
x=torch.randn(3,3)
#1.上三角
y1=torch.triu(x)
print('y1:',y1)
z1=torch.triu(x,1)
print('z1:',z1)
a1=torch.triu(x,-1)
print('a1:',a1)

#2.下三角
y2=torch.tril(x)
print('y2:',y2)
z=torch.tril(x,1)
print('z2:',z2)
a=torch.tril(x,-1)
print('a2:',a2)

y1: tensor([[ 0.3770,  1.2139, -0.9867],
        [ 0.0000,  0.7685,  0.2979],
        [ 0.0000,  0.0000,  1.8912]])
z1: tensor([[ 0.0000,  1.2139, -0.9867],
        [ 0.0000,  0.0000,  0.2979],
        [ 0.0000,  0.0000,  0.0000]])
a1: tensor([[ 0.3770,  1.2139, -0.9867],
        [ 0.3624,  0.7685,  0.2979],
        [ 0.0000, -1.2170,  1.8912]])
y2: tensor([[ 0.3770,  0.0000,  0.0000],
        [ 0.3624,  0.7685,  0.0000],
        [ 0.0577, -1.2170,  1.8912]])


NameError: name 'z2' is not defined

In [19]:
#矩阵乘法
#1.二维矩阵乘法
mat1=torch.randn(2,3)
mat2=torch.randn(3,2)
result=torch.mm(mat1,mat2)
print(result)
#2.3D矩阵乘法（x*n*m 与 x*m*p 得到一个 x*n*p）

mat1=torch.randn(2,3,1)
mat2=torch.randn(2,1,3)
result=torch.bmm(mat1,mat2)
print(result.size())

tensor([[-1.8372, -0.7908],
        [ 0.4884, -0.2368]])
torch.Size([2, 3, 3])


In [22]:
#矩阵转置/逆矩阵
x=torch.randn(3,3)
result1=torch.t(x)
result2=torch.inverse(x)

print(x)
print(result1)
print(result2)

tensor([[-0.0167,  0.0824, -0.0305],
        [-0.7209,  0.2191,  0.3109],
        [ 2.1024,  0.2111, -0.5297]])
tensor([[-0.0167, -0.7209,  2.1024],
        [ 0.0824,  0.2191,  0.2111],
        [-0.0305,  0.3109, -0.5297]])
tensor([[ -4.1205,   0.8441,   0.7324],
        [  6.1616,   1.6528,   0.6157],
        [-13.8994,   4.0093,   1.2644]])


In [24]:
#奇异值分解
x=torch.randn(3,3)
u,s,v=torch.svd(x)
print(u)
print(s)
print(v)


tensor([[-0.6922,  0.4060,  0.5967],
        [-0.2924,  0.5981, -0.7462],
        [-0.6598, -0.6910, -0.2954]])
tensor([1.8716, 1.0757, 0.1674])
tensor([[-0.2488, -0.1193,  0.9612],
        [ 0.8247,  0.4943,  0.2749],
        [-0.5079,  0.8611, -0.0246]])


In [25]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)

In [3]:
print(torch.cuda.is_available())

False
